services:
  app:
    image: us-central1-docker.pkg.dev/taskproject-449320/cloud-app/test-app:latest
    restart: on-failure:5
    container_name: my-app
    ports:
     - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.3.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: cloud_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - "3306:3306"