name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.REGISTRY_JSON }}

      - name: Build Maven Java App Image
        run: |
          docker build -t us-central1-docker.pkg.dev/taskproject-449320/cloud-app/test-app:${{ github.sha }} -f Dockerfile .

      - name: Push Java App Image to Docker Hub
        run: |
          docker push us-central1-docker.pkg.dev/taskproject-449320/cloud-app/test-app:${{ github.sha }}
